name: Release

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Get next version
        id: get_next_version
        uses: thenativeweb/get-next-version@2.7.1

      - name: Setup Go
        if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
        uses: actions/setup-go@v6
        with:
          go-version-file: ./go.mod

      - name: Login to GitHub container registry
        if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: github-actions
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new tag
        if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
        run: |
          git tag ${{ steps.get_next_version.outputs.version }}
          git push origin ${{ steps.get_next_version.outputs.version }}

      - name: Run GoReleaser
        if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}